### ISSUE TITLE
Acceleration should be an incremental force, not an instant force.

### ISSUE THREAD

**Issue by ehgoodenough** [ehgoodenough/gmtk-2017#1]
#thingsinmotiontendtostayinmotion

Currently, when you hit a key to move, we immediately set your velocity to a fixed speed:

```js
if(Keyb.isDown("<up>") || Keyb.isDown("W")) {
    this.velocity.y = -1 * this.speed
}
```

This is unrealistic, since our "acceleration" isn't respecting our previous velocity. If I was actively moving southwards, but then wanted to move northwards, I would first have to overcome my previous southwards velocity. But with this system, I immediately drop my southwards velocity and begin moving northwards.

We should probably adopt an incremental acceleration, where we append to the velocity, like so:

```js
if(Keyb.isDown("<up>") || Keyb.isDown("W")) {
    this.velocity.y -= this.speed
}
```

But that said, I couldn't find a good value for `speed` that didn't feel too floaty. All my attempts at tweaking this felt like I was skating on ice. :\

**Comment by DLMcPherson** [comment]
Resolved this issue by adding Coulomb friction and a dynamic equation for the player. There are now constants for tuning how responsive (quick to speed up) and how skate-y (time to change directions) you want. It feels weird to me right now and that's either a matter of tuning or because I'm a bit peckish right now. Gonna dig into this soup!
